apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-war-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-war-app
  template:
    metadata:
      labels:
        app: java-war-app
    spec:
      containers:
        - name: java-war-app
          image: srikanth169/train-ticket:v1
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: java-war-service
  labels:
    app: java-war-app
spec:
  type: LoadBalancer
  selector:
    app: java-war-app
  ports:
    - port: 80
      targetPort: 8080
